name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install -y libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run:
        - cargo test --verbose
        - rustup toolchain install nightly
        - rustup component add rustfmt
        - cargo +nightly fmt -- --check
