name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: rustup default stable && rustup update
    - name: Install libasound2-dev
      run: sudo apt-get install -y libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install nightly toolchain for rustfmt
      run: rustup toolchain install nightly --allow-downgrade --component rustfmt && rustup default nightly
    - name: Check formatting
      run: cargo fmt -- --check
